nodeLinker: node-modules

# npmAuthToken: "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"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-1.22.19.cjs
