branch-defaults:
  develop:
    environment: 4mwebappdev-env
  main:
    environment: 4mwebapp-env
deploy_dev:
  artifact: ./dev_web_build_artifact.zip
deploy_prod:
  artifact: ./prod_web_build_artifact.zip
environment-defaults:
  4mwebapp-env:
    branch: null
    repository: null
  4mwebappdev-env:
    branch: null
    repository: null
global:
  application_name: 4M Web App Dev
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
