version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/4m-ecommerce-app-web/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ubuntu
